name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Deploy on push to main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # [!code highlight]
        with:
          fetch-depth: 0 # Needed for page update histories

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # [!code highlight]
        with:
          version: 8
          run_install: true # Install with pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4 # [!code highlight]
        with:
          node-version: 20 # Node.js version
          cache: pnpm # Cache pnpm

      - name: Build VuePress site
        run: pnpm build # Build VuePress site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # [!code highlight]
        with:
          path: docs/.vuepress/dist # The directory where the built VuePress site is located

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # [!code highlight]